PULL_REQUEST_TEMPLATE.md

| Check | Author | Reviewer |
|---|---|---|
| PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request) | <ul><li> [ ] </li></ul> | <ul><li> [ ] </li></ul> |
| Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders) | <ul><li> [ ] </li></ul> | <ul><li> [ ] </li></ul> |
| Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions) | <ul><li> [ ] </li></ul> | <ul><li> [ ] </li></ul> |

Add sphere engine check to the PR template

---

solutions/functions/signum.js

Functions - Signum

---

solutions/functions/prime-checker-function.js

Functions - Prime Checker Function

---

solutions/functions/print-with-index.js

Functions - Print With Index

---

solutions/functions/floor-expression.js

Functions - Floor Expression

---

solutions/functions/even-odd-seperator.js

Functions - Even Odd Seperator

---

solutions/functions/brick-volume.js

Functions - Brick Volume

---

solutions/functions/sum-of-multiples.js

Functions - Sum Of Multiples

---

solutions/functions/college.js

Functions - College

---

solutions/functions/pivot-index.js

Functions - Pivot Index

---

solutions/functions/factorial-iterative.js

Functions - Factorial Iterative

---

solutions/functions/modiji.js

Functions - Modiji

---

solutions/functions/min-max-range.js

Functions - Min Max Range

---

solutions/functions/largest.js

Functions - Largest

---

solutions/classes/flight.js

Classes - Flight

---

solutions/classes/person.js

classes - person

---

solutions/classes/shape.js

Classes - shape

---

solutions/classes/area-and-perimeter-of-rectangle.js

Classes - area and perimeter of rectangle

---

solutions/classes/print-movie-description.js

Classes - print movie description

---

solutions/classes/input-reader.js

Classes- input reader

---

solutions/classes/hop-racing.js

Classes - hop racing

---

solutions/classes/robot-movement.js

Classes - robot movement

---

solutions/classes/area-and-perimeter-of-the-circle.js

Classes - area and perimeter of the circle

---

solutions/classes/movie-description-extension.js

Classes - movie description extension

---

solutions/classes/bank-account-debit-credit.js

Classes - bank account debit credit

---

solutions/classes/car-sale-customer.js

Classes - car sale customer

---

solutions/arrays/sum-of-diagonals.js

Arrays - Sum Of Diagonals

---

solutions/arithmetic/sum-of-n-natural-numbers.js

- Solution is tested on sphere engine

Arithmetic - Sum of first n natural numbers

---

solutions/recursion/factorial-recursive.js

Hi,
With my solution 1 test case is failing. I think its because of large number as input leading to memory overflow.
Kindly check and approve.
Regards,
Devjyoti Rakshit

recursion - factorial recursive

---

solutions/recursion/gcd-recursive.js

Recursion - GCD Recursive

---

solutions/recursion/sum-of-first-n.js

Recursion - Sum of first n

---

solutions/recursion/binomial-coefficient.js

Recursion - binomial coefficient

---

solutions/recursion/add-substract.js

recursion - add substract

---

solutions/recursion/recursive-sequence.js

Recursion - Recursive Sequence

---

solutions/recursion/reverse-string-recursive.js

recursion - reverse string recursive

---

solutions/recursion/distance-covering.js

recursion - distance covering

---

solutions/arithmetic/triangle-angle.js

Arithmetics - Triangle Angle

---

solutions/arithmetic/sqaure-sum.js

Arithmetics - Square Sum

---

solutions/arithmetic/mean.js

Arithmetic - Mean

---

solutions/arrays/right-to-left-diagonal
solutions/arrays/right-to-left-diagonal.js

Arrays - right to left diagonal

---

solutions/arrays/len-of-last-word
solutions/arrays/len-of-last-word.js

Arrays - len of last word

---

solutions/arrays/count-odd-even-numbers.js

Arrays - Count Odd Even Numbers
